{ config, pkgs, inputs, ... }:

{
  imports = [
    # Hardware config is generated by `nixos-generate-config` at install
    # time, lives at /etc/nixos/, and is copied into this directory by
    # `make copy-hardware`. Flake pure-eval forbids reading /etc directly,
    # so the copy must live alongside this file. It is NOT committed —
    # each machine has its own (see .gitignore).
    ./hardware-configuration.nix

    ../../modules/nixos/appimage.nix
    ../../modules/nixos/backup.nix
    ../../modules/nixos/boot.nix
    ../../modules/nixos/desktop.nix
    ../../modules/nixos/flatpak.nix
    ../../modules/nixos/fonts.nix
    # Immich now runs via Docker (see compose / dockur stack). Re-enable
    # this import to switch back to the native NixOS service.
    # ../../modules/nixos/immich.nix
    ../../modules/nixos/media.nix
    ../../modules/nixos/networking.nix
    ../../modules/nixos/secrets.nix
    ../../modules/nixos/security.nix
    ../../modules/nixos/system.nix
    ../../modules/nixos/virtualization.nix
    ../../modules/nixos/vpn.nix
  ];

  # TODO: Override the swap device from hardware-configuration.nix to enable
  # random encryption (new key on each boot). Replace <SWAP_LABEL_OR_UUID>
  # with the actual swap label/UUID from your hardware-configuration.nix
  #
  # swapDevices = [{
  #   device = "/dev/disk/by-label/<SWAP_LABEL_OR_UUID>";
  #   randomEncryption.enable = true;
  # }];

  # User profile picture for GDM / AccountsService.
  system.activationScripts.setProfileImages.text = ''
  	for user in /home/*; do
  		user=$(basename "$user")
  		profile="/home/$user/Pictures/profile-picture-small.png"

  		if [ -f "$profile" ]; then
  			cp "$profile" "/var/lib/AccountsService/icons/$user"
  		fi

  		cat <<-EOF > "/var/lib/AccountsService/users/$user"
  			[User]
  			Session=
  			Icon=/var/lib/AccountsService/icons/$user
  			SystemAccount=false
  		EOF
  	done
  '';

  system.stateVersion = "25.11"; # WARNING: DO NOT CHANGE after initial installation
}
