# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "vmd" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-8f60f834-266f-42a7-b957-f2ce818eef28";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-8f60f834-266f-42a7-b957-f2ce818eef28".device = "/dev/disk/by-uuid/8f60f834-266f-42a7-b957-f2ce818eef28";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7E67-7B98";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/luks-330c8af9-5ceb-4758-8b47-5321038b338f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-330c8af9-5ceb-4758-8b47-5321038b338f".device = "/dev/disk/by-uuid/330c8af9-5ceb-4758-8b47-5321038b338f";

  swapDevices =
    [ { device = "/dev/mapper/luks-271ccf8c-bc8d-4b69-938c-19dabd8e3da0"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
